# Site information
title: 'NanoBioMech-AI Lab'
description: 'Integrating Mechanics, Machine Learning, and Biomaterials for Resilient Design.'

# Site header
header:
  navbar:
    enable: true
    logo:
      image: 'icon.png'
    menu:
      main:
        - name: Home
          url: '/'
          weight: 10
        - name: People
          url: '/people/'
          weight: 20
        - name: Research
          url: '/research/'
          weight: 30
        - name: Publications
          url: '/publication/'
          weight: 40
        - name: Contact
          url: '/contact/'
          weight: 50

# Site footer
footer:
  copyright:
    enable: true
    content: 'NanoBioMech-AI Lab'